<?php

declare(strict_types=1);

namespace App\Filament\Resources\PokemonResource\Pages;

use App\Filament\Resources\PokemonResource;
use App\Services\PokeAPIService;
use Filament\Actions\Action;
use Filament\Resources\Pages\ViewRecord;

class ViewPokemon extends ViewRecord
{
    protected static string $resource = PokemonResource::class;

    protected static string $view = 'filament.pokemon.pages.view-pokemon';

    protected function getHeaderActions(): array
    {
        return [
            Action::make('Go back')->action(fn () => $this->redirect('/poke')),
        ];
    }

    public function mount(int|string $record): void
    {
        app(PokeAPIService::class)->verifyRecord($record);
        parent::mount($record); // TODO: Change the autogenerated stub
    }
}
